### ISSUE TITLE
Can't determine status of file

### ISSUE THREAD

**Issue by pchettiy** [ankit-m/project-surat#14]
Unless the file is completely uploaded, we can't say where the file is, whether the file is uploading or not.

Also, the text and the file don't appear together in the list.

**Comment by sahiljain112** [comment]
We are using firebase storage to upload files. Firebase fires a state changed event for every block size of 256 KB. If the file size is lesser than that, then the upload will hit 100% in the first iteration.
I have added a progress bar for files larger than 256 KB. However, this is a temporary fix. Modifications will be made soon.

For the second issue, we have reserved txt for plain text input and file for any files that a user uploads.
